use_frameworks!

platform :ios, '12.0'

target 'MyCocoaPodLibraryBps_Example' do
  pod 'MyCocoaPodLibraryBps', :path => '../'

  target 'MyCocoaPodLibraryBps_Tests' do
    inherit! :search_paths

    
  end
end
